### ISSUE TITLE
Improvements in decryptor.py

### ISSUE THREAD

**Issue by rennaMAhcuS** [AdityaNeeraje/Hill-Cipher-Crypto-LS#1]
The `decryptor.py` program is functioning as expected, but you can try to incorporate these minor changes:
- Take the `plaintext` and `ciphertext` as an **input**.
- Try to output the key as a **matrix**, as mentioned in the **Problem Statement**.
- You could also try to **output all the possible keys** for a given case.

> [!NOTE]
> These are just some minor suggestions from my side 🙂.

**Mohana, CSeC CTM**

**Comment by AdityaNeeraje** [comment]
Sure. I implemented both of them and pushed it. Thanks for the suggestion.

**Comment by rennaMAhcuS** [comment]
👍
"Take the `plaintext` and `ciphertext` as input." - This would complete this issue thread. I am closing this issue.

> The code was executed flawlessly, and the task was accomplished without issues.
> 👏
